// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOWlL4OY22WbvqL2C849tAW8ByFLOpZTc',
    appId: '1:635414448004:web:b507c43ac287dafa183fd1',
    messagingSenderId: '635414448004',
    projectId: 'petrdrop-284dd',
    authDomain: 'petrdrop-284dd.firebaseapp.com',
    storageBucket: 'petrdrop-284dd.appspot.com',
    measurementId: 'G-X09Z5TLFMV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJZc0qf8SfP_jBySIebBIhjp4fe_gFCLk',
    appId: '1:635414448004:android:fe56cd881909a6a5183fd1',
    messagingSenderId: '635414448004',
    projectId: 'petrdrop-284dd',
    storageBucket: 'petrdrop-284dd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHFXEzOROnp8G27SjleKUArvCaBiyFEow',
    appId: '1:635414448004:ios:00936241649deb2b183fd1',
    messagingSenderId: '635414448004',
    projectId: 'petrdrop-284dd',
    storageBucket: 'petrdrop-284dd.appspot.com',
    iosBundleId: 'com.example.petrDropApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHFXEzOROnp8G27SjleKUArvCaBiyFEow',
    appId: '1:635414448004:ios:1e7d4db759398c3b183fd1',
    messagingSenderId: '635414448004',
    projectId: 'petrdrop-284dd',
    storageBucket: 'petrdrop-284dd.appspot.com',
    iosBundleId: 'com.example.petrDropApplication.RunnerTests',
  );
}
